services:

  postgres:
    image: postgres:16-alpine
    container_name: cloudops360-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: cloudops360-backend:1.0
    container_name: cloudops-api
    restart: unless-stopped

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "148:5000"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/api/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: cloudops360-frontend:1.0
    container_name: cloudops360-cont
    restart: unless-stopped

    ports:
      - "145:80"

    depends_on:
      backend:
        condition: service_healthy


volumes:
  postgres_data: