services:

  postgres:
    image: postgres:16-alpine
    container_name: cloudops360-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cloudops360
      POSTGRES_USER: cloudops
      POSTGRES_PASSWORD: cloudops_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudops -d cloudops360"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: